export interface ZModel {
  id: string
  name: string
  subtitle?: string
  years: string
  chassis: string
  bodyStyle: string
  image: string
  powerRange: string
  facts: string[]
  specialEditions?: string[]
  isFacelift?: boolean
  faceliftChanges?: string[]
}

export const zModels: ZModel[] = [
  {
    id: 'z1',
    name: 'Z1',
    years: '1989-1991',
    chassis: 'Z1 (E30-related)',
    bodyStyle: 'Roadster',
    image: '/images/z1.png',
    powerRange: '170 hp',
    facts: [
      'Revolutionary sliding doors that retract vertically into the body',
      'Only 8,000 units produced over its entire production run',
      'First BMW to use the "Z" designation for roadsters',
      'Thermoplastic body panels could be removed in just 40 minutes',
      'Developed by BMW Technik GmbH as a technology showcase',
    ],
    specialEditions: ['Sliding-door original Z car'],
  },
  {
    id: 'z3-roadster',
    name: 'Z3',
    subtitle: 'Roadster',
    years: '1995-2002',
    chassis: 'E36/7',
    bodyStyle: 'Roadster',
    image: '/images/z3-roadster.png',
    powerRange: '140-225 hp',
    facts: [
      'Star of the James Bond film "GoldenEye" (1995)',
      'First BMW built in the United States (Spartanburg, SC)',
      'Based on the E36 3 Series platform',
      'Over 290,000 units produced during its entire run',
      '2000 facelift added wider rear fenders and revised styling',
    ],
    specialEditions: ['James Bond Edition', '007 Special Edition'],
  },
  {
    id: 'z3-m',
    name: 'Z3',
    subtitle: 'M Roadster',
    years: '1997-2002',
    chassis: 'E36/7',
    bodyStyle: 'Roadster',
    image: '/images/z3-m.png',
    powerRange: '321-325 hp',
    facts: [
      'Powered by the legendary S50/S52 and later S54 inline-6',
      'Post-2001 models received the S54 engine from E46 M3',
      'Wider rear fenders to accommodate larger wheels and tires',
      'Aggressive quad exhaust tips became signature styling',
      'One of the most sought-after modern BMW collectibles',
    ],
    specialEditions: ['M Roadster S52', 'M Roadster S54'],
  },
  {
    id: 'z3-coupe',
    name: 'Z3',
    subtitle: 'Coupe',
    years: '1998-2002',
    chassis: 'E36/8',
    bodyStyle: 'Coupe',
    image: '/images/z3-coupe.png',
    powerRange: '321-325 hp',
    facts: [
      'Earned the legendary nickname "Clown Shoe"',
      'Significantly stiffer chassis than the Roadster',
      'Designed by an engineer as a personal project',
      'Trunk space made it surprisingly practical',
      'Now commands premium prices among collectors',
    ],
    specialEditions: ['M Coupe S52', 'M Coupe S54'],
  },
  {
    id: 'z8',
    name: 'Z8',
    years: '1999-2003',
    chassis: 'E52',
    bodyStyle: 'Roadster',
    image: '/images/z8.png',
    powerRange: '400 hp',
    facts: [
      'Designed by Henrik Fisker as modern interpretation of the 507',
      'Featured in James Bond "The World Is Not Enough"',
      'Aluminum space frame construction',
      'Only 5,703 units produced worldwide',
      'Shared its S62 V8 engine with the E39 M5',
    ],
    specialEditions: ['Alpina Roadster V8 (555 units)'],
  },
  {
    id: 'z4-e85-roadster',
    name: 'Z4',
    subtitle: 'E85 Roadster',
    years: '2002-2008',
    chassis: 'E85',
    bodyStyle: 'Roadster',
    image: '/images/z4-e85-roadster.png',
    powerRange: '192-265 hp',
    facts: [
      'Designed by Chris Bangle with "flame surfacing"',
      'Electric soft-top operation standard',
      'Significantly improved chassis stiffness over Z3',
      'Featured run-flat tires as standard equipment',
      '2006 facelift brought N52 engine and revised styling',
    ],
    specialEditions: ['Alpina Roadster S', '3.0si'],
  },
  {
    id: 'z4-e85-m',
    name: 'Z4',
    subtitle: 'M Roadster',
    years: '2006-2008',
    chassis: 'E85',
    bodyStyle: 'Roadster',
    image: '/images/z4-e85-m.png',
    powerRange: '343 hp',
    facts: [
      'Powered by the legendary S54 inline-6 from E46 M3',
      'Manual transmission only - a purist approach',
      'M-tuned suspension, brakes, and differential',
      'Produced for only two years, making it rare',
      'Regarded as one of the best driver Z cars ever made',
    ],
    specialEditions: ['Z4 M Roadster'],
  },
  {
    id: 'z4-e85-coupe',
    name: 'Z4',
    subtitle: 'Coupe',
    years: '2006-2008',
    chassis: 'E86',
    bodyStyle: 'Coupe',
    image: '/images/z4-e85-coupe.png',
    powerRange: '343 hp',
    facts: [
      'Spiritual successor to the Z3 M Coupe',
      'Same S54 engine as M Roadster, 343 hp',
      'Fixed roof provides even more chassis rigidity',
      'Became instant collector car upon release',
      'Limited production makes it highly desirable',
    ],
    specialEditions: ['Z4 M Coupe'],
  },
  {
    id: 'z4-e89',
    name: 'Z4',
    subtitle: 'E89',
    years: '2009-2016',
    chassis: 'E89',
    bodyStyle: 'Retractable Hardtop',
    image: '/images/z4-e89-roadster.png',
    powerRange: '184-340 hp',
    facts: [
      'First Z4 with a retractable hardtop',
      'Hardtop transforms in just 20 seconds',
      'First twin-turbo inline-6 in a Z roadster',
      'No dedicated M model offered this generation',
      '2013 facelift updated styling and added 4-cylinder',
    ],
    specialEditions: ['sDrive35is (340 hp)', 'Pure Fusion Design'],
  },
  {
    id: 'z4-g29',
    name: 'Z4',
    subtitle: 'G29',
    years: '2018-2026',
    chassis: 'G29',
    bodyStyle: 'Soft-top Roadster',
    image: '/images/z4-g29-roadster.png',
    powerRange: '197-387 hp',
    facts: [
      'Co-developed with Toyota (Supra A90 sibling)',
      'Return to traditional soft-top design',
      'M40i offers M Performance power with 387 hp',
      'Produced at Magna Steyr in Austria',
      '2022 facelift added BMW Curved Display and iDrive 8',
    ],
    specialEditions: ['M40i First Edition', 'Final Edition (2026)'],
  },
]
